### ISSUE TITLE
Add a "I'm new to this" or "experience level" field to kompo entries?

### ISSUE THREAD

**Issue by teistiz** [Instanssi/Instanssi.org#50]
We may want to award the best newcomer separately instead of creating new compos just for that.

Is there any danger of someone trolling the compo with this?

**Comment by katajakasa** [comment]
Back in the day, I used to play Age of Empires II in Internet Gaming Zone. There were games called "Noobs only". The players were invariably people who just wanted to smash beginners.

My vote here is no, because anyone can just tell the system he's a "beginner" and potentially get preferential treatment.

**Comment by katajakasa** [comment]
I think this hasn't been asked for since... Closing this, let's reopen if this gets requested again.-
